version: '3'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/docker
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - $HOME/jenkins-data/jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  git:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '10.128.16.209' # change, ip of server 
    ports:
      - '80:80'
      - '443:443'
      - '2002:22'
    volumes:
      - '$HOME/gitlab/config:/etc/gitlab'
      - '$HOME/gitlab/logs:/var/log/gitlab'
      - '$HOME/gitlab/data:/var/opt/gitlab'
    networks:
      - net
networks:
  net:
