version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - $HOME/jenkins-data/jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  git:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    hostname: '192.168.100.111' # change, ip of server 
    ports:
      - '80:80'
      - '443:443'
      - '2002:22'
    volumes:
      - '$HOME/gitlab/config:/etc/gitlab'
      - '$HOME/gitlab/logs:/var/log/gitlab'
      - '$HOME/gitlab/data:/var/opt/gitlab'
    networks:
      - net
  portainer:
    container_name: portainer
    image: 'portainer/portainer:latest'
    ports:
      - ':9100:9000'
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
      - '$HOME/portainer:/data'
    networks:
      - net
  uptime-kuma:
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:latest'
    ports:
      - '3001:3001'
    volumes:
      - '$HOME/uptime-kuma/data:/app/data'
    networks:
      - net
networks:
  net:
